title: Eclipse Xpect
url: "https://www.eclipse.org"
baseurl: /xpect

collections:
  staff_members:
    output: false

exclude: 
  - "Gemfile"
  - "Gemfile.lock"
  - "README.md"
  - "Rakefile"
  - vendor

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: "index.html"
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: "gettingstarted.html"
      type: "pages"
    values:
      layout: "default"
